// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendix.actions;

import mendix.proxies.DTAP_Enum;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Java_GetDTAP extends CustomJavaAction<java.lang.String>
{
	public Java_GetDTAP(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (Core.getConfiguration().isInDevelopment()) {
			return DTAP_Enum.Development.toString();
		} else if (!Core.getConfiguration().isInDevelopment()) { // Not sure other options that are not in development will be tested
			return DTAP_Enum.Test.toString();					// This might not be the right fix
		} else  if (!Core.getConfiguration().isInDevelopment()) {
			return DTAP_Enum.Acceptance.toString();
		} else  if (!Core.getConfiguration().isInDevelopment()) {
			return DTAP_Enum.Production.toString();
		} else if (!Core.getConfiguration().isInDevelopment()) {
			return DTAP_Enum.Test.toString();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Java_GetDTAP";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
